# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kassen Dauren - simple achievements
emaillink: kas.dauren@gmail.com
email: ✉️ kas.dauren@gmail.com
facebooklink: https://web.facebook.com/profile.php?id=100006326387722
facebook: ✉️ Kas
instagramlink: https://www.instagram.com/kassiend_/
instagram: 📷 @kassiend_
description:  Mobile application developer focused on improving skills and on acquiring new skills.
              Almost 2-years in mobile application development.
              Successfully finished many projects.
              Looking forward to apply my knowledge and keep acquiring new experiences .
baseurl: "https://kasss.github.io" # the subpath of your site, e.g. /blog
url: "https://kasss.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  Kasss
footer_title: kasss.github.io
# Build settings
markdown: kramdown
